export * from './isAlias';
export * from './isBrand';
export * from './isCmp';
export * from './isFigmaBase';
export * from './isFigmaScheme';
export * from './isGlobal';
export * from './isGroup';
export * from './isNotFigma';
export * from './isCmpAlias';
